/// Plain-text / source-like extensions aligned with frontend `TEXT_EXTENSIONS` + `txt`.
/// Used only by duplicate scan when `include_plain_text_in_duplicate_scan` is false.
pub fn is_text_like_extension(ext: &str) -> bool {
    let e = ext.trim_start_matches('.').to_lowercase();
    matches!(
        e.as_str(),
        "txt"
            | "md"
            | "markdown"
            | "js"
            | "mjs"
            | "cjs"
            | "ts"
            | "jsx"
            | "tsx"
            | "json"
            | "jsonc"
            | "yaml"
            | "yml"
            | "html"
            | "htm"
            | "css"
            | "scss"
            | "sass"
            | "xml"
            | "csv"
            | "tsv"
            | "sql"
            | "sh"
            | "bash"
            | "zsh"
            | "ps1"
            | "env"
            | "ini"
            | "conf"
            | "config"
            | "toml"
            | "py"
            | "rs"
            | "java"
            | "c"
            | "cpp"
            | "h"
            | "hpp"
            | "go"
            | "php"
            | "rb"
            | "swift"
            | "kt"
            | "dart"
            | "r"
            | "lua"
            | "pl"
    )
}
